;;!! Android tasks

(define-task android:setup ()
  ;; Set up Android project files
  (fusion#android-project-set-target "android-15")
  ;; Create symlink to SDL library from SDL2 Sphere
  (let ((SDL-link (string-append (android-jni-generator-directory) "deps/SDL")))
    (unless (file-exists? SDL-link)
            (create-symbolic-link (string-append (%sphere-path 'sdl2) "deps/SDL2-2.0.3") SDL-link))))

(define-task android:compile ()
  (fusion#android-compile-app "main" 'main
                              target: 'debug
                              cond-expand-features: '(debug)
                              compiler-options: '(debug)))

(define-task android:install ()
  (fusion#android-install 'debug))

(define-task android:run ()
  ;; Run the Activity
  (fusion#android-run "org.libsdl.app/org.libsdl.app.SDLActivity")
  ;; log cat
  (shell-command (string-append (android-adb-path) " logcat *:S *:F SchemeSpheres SDL SDL/APP")))

(define-task android (android:compile android:install android:run)
  'android)

(define-task android:clean ()
  (fusion#android-clean))

;;!! iOS tasks

(define ios-directory
  (make-parameter "ios/"))

(define-task ios:setup ()
  ;; Create symlink to SDL include library from SDL2 Sphere
  (let ((SDL-link (string-append (ios-directory) "SDL/include")))
    (unless (file-exists? SDL-link)
            (create-symbolic-link (string-append (%sphere-path 'sdl2) "deps/SDL2-2.0.3/include") SDL-link))))

;;! Compile App
;; .parameter main-module main-module of the Android App
;; .parameter import-modules modules already generated to be linked as well
(define (fusion#ios-compile-app app-name
                                main-module
                                #!key
                                (cond-expand-features '())
                                (compiler-options '())
                                (version compiler-options)
                                (compiled-modules '())
                                (jni-files '())
                                (target 'debug)
                                (verbose #f))
  ;; Defines
  (##cond-expand-features (append '(mobile android) (##cond-expand-features)))

  ;; Checks
  ;; (fusion#android-installed?)
  ;; (fusion#android-project-supported?)
  ;; ;; Compute dependencies
  ;; (let* ((modules-to-compile (append (%module-deep-dependencies-to-load main-module) (list main-module)))
  ;;        (all-modules (append compiled-modules modules-to-compile)))
  ;;   ;; List files generated by compiling modules, C files from the JNI, and the linkfile
  ;;   (let ((all-c-files
  ;;          (append (map (lambda (m) (string-append "../" (android-build-directory-suffix)
  ;;                                             (%module-filename-c m version: version)))
  ;;                       all-modules)
  ;;                  (list (string-append "../" (android-build-directory-suffix) (android-link-file)))
  ;;                  jni-files)))
  ;;     ;; Create Android build directory if it doesn't exist
  ;;     (unless (file-exists? (android-build-directory))
  ;;             (make-directory (android-build-directory)))
  ;;     ;; Create Android assets directory if it doesn't exist
  ;;     (unless (file-exists? (android-base-assets-directory-suffix))
  ;;             (make-directory (android-base-assets-directory-suffix)))
  ;;     (unless (file-exists? (android-assets-directory))
  ;;             (make-directory (android-assets-directory)))
  ;;     (let ((arguments '(app-name main-module-name c-files-string))
  ;;           (arg-values `("main"
  ;;                         "main"
  ;;                         ,(apply string-append (map (lambda (file) (string-append file " ")) all-c-files)))))
  ;;       ;; Process 'assets'
  ;;       (fusion#process-directory-with-templates (android-assets-directory)
  ;;                                                "assets/"
  ;;                                                arguments
  ;;                                                arg-values)
  ;;       ;; Process 'src'
  ;;       (fusion#process-directory-with-templates (android-src-directory)
  ;;                                                (string-append (android-directory) (android-src-generator-directory-suffix))
  ;;                                                arguments
  ;;                                                arg-values)
  ;;       ;; Process 'jni'. Make sure Android.mk is updated if config.scm is more recent than Android.mk
  ;;       (fusion#process-directory-with-templates (android-jni-directory)
  ;;                                                (string-append (android-directory) (android-jni-generator-directory-suffix))
  ;;                                                arguments
  ;;                                                arg-values
  ;;                                                ;; force overwriting Android.mk if config.scm is newer
  ;;                                                overwrite-files:
  ;;                                                (let ((android-mk
  ;;                                                       (string-append (android-directory) "jni/src/Android.mk")))
  ;;                                                  (if ((newer-than? android-mk)
  ;;                                                       (string-append (current-directory) "config.scm"))
  ;;                                                      (begin
  ;;                                                        (info/color 'yellow "Android.mk updated due to changes in config.scm")
  ;;                                                        (list android-mk))
  ;;                                                      '()))))
  ;;     ;; Generate modules (generates C code)
  ;;     (let ((something-generated? #f))
  ;;       (for-each (lambda (m)
  ;;                   (if ((newer-than? (string-append (android-build-directory)
  ;;                                                    (%module-filename-c m version: version)))
  ;;                        (string-append (%module-path-src m) (%module-filename-scm m)))
  ;;                       (begin
  ;;                         (set! something-generated? #t)
  ;;                         (sake#compile-to-c m
  ;;                                            cond-expand-features: (append cond-expand-features '(android mobile))
  ;;                                            compiler-options: compiler-options
  ;;                                            verbose: verbose))))
  ;;                 modules-to-compile)
  ;;       (if something-generated?
  ;;           (info/color 'blue "generating C files")
  ;;           (info/color 'blue "no Scheme files need C recompilation"))
  ;;       ;; Copy C files from both compiled and imported modules into android build directory (if updated)
  ;;       (for-each
  ;;        (lambda (m) (let ((source (string-append (current-build-directory)
  ;;                                            (%module-filename-c m version: version)))
  ;;                     (destination (string-append (android-build-directory)
  ;;                                                 (%module-filename-c m version: version))))
  ;;                 (if ((newer-than? destination) source)
  ;;                     (copy-file source destination))))
  ;;        all-modules)
  ;;       ;; Generate link file
  ;;       (if something-generated?
  ;;           (fusion#android-generate-link-file all-modules version: version))))
  ;;   (info/color 'blue "compiling JNI C/Scheme code")
  ;;   ;; Call "ndk-build". We dump the output to a file, as Gambit has issues with the "-j" flag for concurrent compilation
  ;;   (unless (zero? (shell-command (string-append (android-ndk-build-path) " -C " (android-directory))))
  ;;           (err "error building native code\n\n"))
  ;;   #;(unless (zero? (shell-command (string-append (android-ndk-build-path) " -j -C " (android-directory) " &>ndk-log")))
  ;;   (err "error building native code\n\n" (sake#read-file "ndk-log")))
  ;;   (if verbose (display (sake#read-file "ndk-log")))
  ;;   (info/color 'blue "compiling Java code")
  ;;   ;; Call "ant"
  ;;   (unless (zero? (shell-command (string-append (host-ant-path) " -s " (android-directory) "build.xml "
  ;;                                                (cond ((eq? 'debug target) "debug")
  ;;                                                      ((eq? 'release target) "release")
  ;;                                                      (else (err "Unknown target parameter: fusion#android-compile-app"))))))
  ;;           (err "error building Java code")))
  )

(define-task ios:compile ()
  (fusion#ios-compile-app "main" 'main
                          target: 'debug
                          cond-expand-features: '(debug)
                          compiler-options: '(debug)))

(define-task ios:install ()
  (fusion#ios-install 'debug))

;; (define-task android:run ()
;;   'run)

;; (define-task ios (ios:compile ios:install ios:run)
;;   'ios)

;; (define-task ios:clean ()
;;   (fusion#ios-clean))

;;!! Host tasks

(define-task host:run ()
  (fusion#host-run-interpreted 'main)) 

(define-task host:compile ()
  (fusion#host-compile-exe "main" 'main))

(define-task host:clean ()
  (sake#default-clean))

(define-task host (host:run)
  'host)

;;!! Default task

(define help #<<end-of-help
  
  Tasks (run with 'sake <task>')
  ------------------------------
  
  android:setup             Setup Android project before running other tasks
  android:compile           Compile Android project
  android:install           Install App in current Android device (hardware or emulated)
  android:run               Run App in current Android device
  android:clean             Clean all Android generated files
  android                   Execute compile, install, run

  ios:setup                 Setup iOS project before running other tasks
  ios:compile               Compile Scheme code that will be embedded in iOS app
  ios:xcode                 Open the iOS project in Xcode
  ios:clean                 Clean all iOS generated files
  ios                       Execute compile task and run Xcode
  
  host:compile              Compile the host program as standalone
  host:run                  Run the host OS (Linux/OSX) program interpreted
  host:clean                Clean the generated host program files
  host                      Defaults to host:run

end-of-help
)

(define-task all ()
  (println help))
