#error "The version indicated in ___VERSION is not supported by gambit.h"
#error "You are probably compiling C code generated by a Gambit compiler earlier or later than v4.7.2"
#error "___VERSION will be set to 407002 to reduce other errors"
#undef ___VERSION
#define ___VERSION 407002
#include "gambit.h"
